import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const inputStyling =
  "border-2 border-indigo-200 rounded-md  hover:border-dotted";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <a href="/login">
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        {/* <Events/> */}
        {/* <JobAdverts/> */}
        {/* <NCInfo/> */}
        {/* <Partner/> */}
        {/* <Board/> */}
      </main>
    </div>
  );
};

export default Home;
